// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzLm3Wv_WuWy_tjZiCmhibWk7IwW5igtM',
    appId: '1:963611045611:web:3a15e62546590bc17018ae',
    messagingSenderId: '963611045611',
    projectId: 'bustrackingapp-95ecc',
    authDomain: 'bustrackingapp-95ecc.firebaseapp.com',
    databaseURL: 'https://bustrackingapp-95ecc-default-rtdb.firebaseio.com',
    storageBucket: 'bustrackingapp-95ecc.firebasestorage.app',
    measurementId: 'G-ZQMTNS1CXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDugLOVuT5g-hm68tGGiy9B1i2CWOF9OFo',
    appId: '1:963611045611:android:3dcf5e3efc95174b7018ae',
    messagingSenderId: '963611045611',
    projectId: 'bustrackingapp-95ecc',
    databaseURL: 'https://bustrackingapp-95ecc-default-rtdb.firebaseio.com',
    storageBucket: 'bustrackingapp-95ecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn7jeIrMaoqazTMCtcGlRvCS-8Lk7xMFM',
    appId: '1:963611045611:ios:6f17651640fcffe27018ae',
    messagingSenderId: '963611045611',
    projectId: 'bustrackingapp-95ecc',
    databaseURL: 'https://bustrackingapp-95ecc-default-rtdb.firebaseio.com',
    storageBucket: 'bustrackingapp-95ecc.firebasestorage.app',
    iosBundleId: 'com.example.busTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn7jeIrMaoqazTMCtcGlRvCS-8Lk7xMFM',
    appId: '1:963611045611:ios:6f17651640fcffe27018ae',
    messagingSenderId: '963611045611',
    projectId: 'bustrackingapp-95ecc',
    databaseURL: 'https://bustrackingapp-95ecc-default-rtdb.firebaseio.com',
    storageBucket: 'bustrackingapp-95ecc.firebasestorage.app',
    iosBundleId: 'com.example.busTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzLm3Wv_WuWy_tjZiCmhibWk7IwW5igtM',
    appId: '1:963611045611:web:4773d2eb96722fce7018ae',
    messagingSenderId: '963611045611',
    projectId: 'bustrackingapp-95ecc',
    authDomain: 'bustrackingapp-95ecc.firebaseapp.com',
    databaseURL: 'https://bustrackingapp-95ecc-default-rtdb.firebaseio.com',
    storageBucket: 'bustrackingapp-95ecc.firebasestorage.app',
    measurementId: 'G-VCF4B405VC',
  );
}
